import { createClient } from "jsr:@supabase/supabase-js@2";
const url=Deno.env.get("SUPABASE_URL")!; const key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!; const db=createClient(url,key);
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"GET, POST, OPTIONS"};
const json=(x:any,s=200)=>new Response(JSON.stringify(x),{status:s,headers:{...cors,"Content-Type":"application/json; charset=utf-8"}}); const ok=(data:any,msg="")=>json({status:"success",message:msg,data}); const fail=(message:string,s=400)=>json({status:"error",message},s);
const text=(v:any)=>String(v??"").trim(); const num=(v:any,d=0)=>Number.isFinite(Number(v))?Number(v):d;
async function master(ward:string){if(!ward)throw Error("กรุณาระบุหน่วยงาน");const {data,error}=await db.from("cloth_master").select("item_name,main_category,par_level").eq("ward",ward).eq("is_active",true).order("main_category").order("item_name");if(error)throw error;return (data||[]).map((r:any)=>({itemName:r.item_name,category:r.main_category||r.item_name,mainCategory:r.main_category||r.item_name,parLevel:num(r.par_level)}));}
async function allLogs(){const {data,error}=await db.from("cloth_count_logs").select("*").order("counted_at",{ascending:false});if(error)throw error;const {data:m,error:me}=await db.from("cloth_master").select("ward,par_level").eq("is_active",true);if(me)throw me;const wardCriteria:any={};for(const r of m||[])wardCriteria[r.ward]=(wardCriteria[r.ward]||0)+num(r.par_level);const allWards=[...new Set((m||[]).map((r:any)=>r.ward).filter(Boolean))];return {data:(data||[]).map((r:any)=>({timestamp:r.counted_at,quarter:r.round_label,ward:r.ward,itemName:r.item_name,mainCategory:r.main_category,readyStock:r.ready_stock,inUse:r.in_use,inLaundry:r.in_laundry,pendingTracking:r.pending_tracking,total:r.total_counted,par:r.par_level,diff:r.difference,recorder:r.recorder,note:r.note})),wardCriteria,allWards};}
async function submitCount(b:any){const ward=text(b.ward),rec=text(b.recorder),round=text(b.quarter);const logs=Array.isArray(b.logs)?b.logs:[];if(!ward||!rec||!logs.length)throw Error("ข้อมูลตรวจนับไม่ครบ");const rows=logs.map((l:any)=>{const ready=num(l.readyStock),use=num(l.inUse),laundry=num(l.inLaundry),pending=num(l.pendingTracking),total=num(l.totalCounted,ready+use+laundry+pending),par=num(l.parLevel),diff=num(l.difference,total-par);return {ward,round_label:round,item_name:text(l.itemName),main_category:text(l.mainCategory||l.category||l.itemName),ready_stock:ready,in_use:use,in_laundry:laundry,pending_tracking:pending,total_counted:total,par_level:par,difference:diff,recorder:rec,note:text(l.note||b.note),count_model:text(b.countModel)||"hospital_v2"};}).filter((r:any)=>r.item_name);if(!rows.length)throw Error("ไม่พบรายการตรวจนับ");const {data:existing,error:ee}=await db.from("cloth_count_logs").select("id").eq("ward",ward).eq("round_label",round).limit(1);if(ee)throw ee;if((existing||[]).length)throw Error("หน่วยงานนี้บันทึกข้อมูลในรอบนี้แล้ว");const {data,error}=await db.from("cloth_count_logs").insert(rows).select("id");if(error)throw error;return {count:(data||[]).length,quarter:round};}
async function tracking(b:any){let q=db.from("cloth_tracking").select("*").order("reported_at",{ascending:false});if(text(b.ward))q=q.eq("ward",text(b.ward));if(text(b.status))q=q.eq("status",text(b.status));const {data,error}=await q;if(error)throw error;return (data||[]).map((r:any)=>({id:r.id,timestamp:r.reported_at,reportDate:r.report_date,ward:r.ward,itemName:r.item_name,mainCategory:r.main_category,qty:r.qty,reason:r.reason,note:r.note,reporter:r.reporter,status:r.status,followupNote:r.followup_note,updatedBy:r.updated_by,updatedAt:r.updated_at}));}
async function submitTracking(b:any){const ward=text(b.ward),date=text(b.reportDate),reporter=text(b.reporter),item=text(b.itemName),reason=text(b.reason),qty=num(b.qty);if(!ward||!date||!reporter||!item||!reason||qty<1)throw Error("ข้อมูลรายการติดตามไม่ครบ");const {data:m}=await db.from("cloth_master").select("main_category").eq("ward",ward).eq("item_name",item).maybeSingle();const {data,error}=await db.from("cloth_tracking").insert({report_date:date,ward,item_name:item,main_category:m?.main_category||item,qty,reason,note:text(b.note)}).select("id,reported_at").single();if(error)throw error;return {id:data.id,timestamp:data.reported_at};}
async function updateTracking(b:any){const id=text(b.id),status=text(b.status),by=text(b.updatedBy);if(!id||!by||!["open","in_progress","returned","lost","cancelled"].includes(status))throw Error("ข้อมูลสถานะไม่ถูกต้อง");const {data,error}=await db.from("cloth_tracking").update({status,followup_note:text(b.followupNote),updated_by:by}).eq("id",id).select("id,status,updated_at").single();if(error)throw error;return data;}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{if(req.method==="GET"){const u=new URL(req.url),a=u.searchParams.get("action");if(a==="getClothMaster")return ok(await master(text(u.searchParams.get("ward"))));if(a==="getAllClothLogs")return ok(await allLogs());if(a==="getClothTracking")return ok(await tracking({ward:u.searchParams.get("ward"),status:u.searchParams.get("status")}));return fail("ไม่รู้จัก action",404);}const b=await req.json();if(b.action==="submitClothLog")return ok(await submitCount(b),"บันทึกการตรวจนับเรียบร้อยแล้ว");if(b.action==="submitClothTracking")return ok(await submitTracking(b),"ส่งรายการติดตามเรียบร้อยแล้ว");if(b.action==="updateClothTrackingStatus")return ok(await updateTracking(b),"อัปเดตสถานะเรียบร้อยแล้ว");return fail("ไม่รู้จัก action",404);}catch(e){console.error(e);return fail(e instanceof Error?e.message:String(e),500);}});
